import React from 'react';
import { X, ShieldAlert, Zap, Info } from 'lucide-react';

interface InfoModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const InfoModal: React.FC<InfoModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div 
        className="bg-white w-full max-w-sm rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200 flex flex-col max-h-[85vh]"
        role="dialog"
        aria-modal="true"
      >
        <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50 sticky top-0 z-10">
          <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2">
            <Info className="text-eco-600" size={20} />
            About WasteBoz Scanner
          </h2>
          <button 
            onClick={onClose} 
            className="p-2 rounded-full hover:bg-slate-200 text-slate-500 transition-colors"
            aria-label="Close info"
          >
            <X size={20} />
          </button>
        </div>
        
        <div className="p-6 space-y-6 overflow-y-auto overscroll-contain">
          
          <div className="space-y-3">
            <h3 className="font-bold text-slate-800 text-sm uppercase tracking-wide flex items-center gap-2">
              <Zap size={16} className="text-amber-500" />
              What is this?
            </h3>
            <p className="text-slate-600 text-sm leading-relaxed">
              WasteBoz Scanner is a smart assistant designed for waste management professionals and businesses. It helps you quickly identify European Waste Catalogue (EWC) codes using simple keywords or by analyzing photos of waste.
            </p>
          </div>

          <div className="space-y-3">
            <h3 className="font-bold text-slate-800 text-sm uppercase tracking-wide">How it works</h3>
            <div className="text-sm text-slate-600 space-y-3">
              <div className="flex gap-3">
                <div className="w-6 h-6 rounded-full bg-eco-100 text-eco-700 flex items-center justify-center font-bold text-xs shrink-0">1</div>
                <p>Type a description (e.g., "mixed construction waste") or take a clear photo of the material.</p>
              </div>
              <div className="flex gap-3">
                <div className="w-6 h-6 rounded-full bg-eco-100 text-eco-700 flex items-center justify-center font-bold text-xs shrink-0">2</div>
                <p>Our AI analyzes the input against the EWC database to find the best matches.</p>
              </div>
              <div className="flex gap-3">
                <div className="w-6 h-6 rounded-full bg-eco-100 text-eco-700 flex items-center justify-center font-bold text-xs shrink-0">3</div>
                <p>Review the codes, checking for hazardous indicators (*).</p>
              </div>
            </div>
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
            <h4 className="font-bold text-slate-800 text-xs uppercase mb-2">Privacy Note</h4>
            <p className="text-xs text-slate-500 leading-relaxed">
              Images are processed in real-time by the AI model and are not permanently stored by this application.
            </p>
          </div>

          <div className="bg-amber-50 border border-amber-100 rounded-xl p-4 flex gap-3">
            <ShieldAlert className="text-amber-600 shrink-0" size={20} />
            <div className="space-y-1">
              <h4 className="font-bold text-amber-800 text-xs uppercase">Important Disclaimer</h4>
              <p className="text-xs text-amber-700 leading-relaxed">
                Results are generated by AI and may be inaccurate. This tool is for guidance only. Always verify codes with official environmental regulations and certified waste management professionals before disposal.
              </p>
            </div>
          </div>
          
        </div>

        <div className="p-4 bg-slate-50 border-t border-slate-100 text-center sticky bottom-0 z-10">
          <button 
            onClick={onClose}
            className="w-full py-3 bg-slate-900 text-white font-bold rounded-xl active:scale-95 transition-transform hover:bg-slate-800 shadow-lg shadow-slate-200"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};